### ISSUE TITLE
Indie Project Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by distillers86** [timzschernitz/pokerStats#1]
@pawaitemadisoncollege

Hi Paula, I've updated my indie project's read me with details requested for check point 1.  I've also added a folder in the root directory called project-flow-and-wireframes with PDFs as well.  If there's anything else I need or any feedback, please let me know.

Thank you!

**Comment by pawaitemadisoncollege** [comment]
This looks like it will be a really fun and useful project @timzschernitz. You've clearly put some good thought into this so far, and you are off to a good start!

A few things to consider:

- [ ] It may be helpful to place the various user stories into your plan. 
- [ ] With regard to login (authentication/authorization) - we will cover this in week 7.  You won't need to write anything for this that connects to the backend (Tomcat will take care of this for us). I wanted to mention this so you don't build anything that's not necessary.
- [ ] I completely understand the concern with your host not wanting to completely open up the application for you to use/test.  An alternative would be to mock this out with a service such as https://www.mockaroo.com.  This can be really useful when we don't yet have access to a service we are planning to use. Mockaroo or a similar service would make a great prof dev presentation too!  An alternative to using a web service would be to use a java library - something like Javamail could provide email functionality to your application, for example (user reporting bad data).
