### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by salamarche** [timzschernitz/pokerStats#2]
# Design/Code Review 1

### Reviewer: Simone

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| Succinct and effective. In the end of the first paragraph "historical statistical tracking" threw me off a little bit. I assume it's referring to a user's data history but for a second I thought that it had to do with something in the actual field of statistics. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | Killer app flow diagram and very cool that you're implementing a kanban board. Everything is really thought out and that's great. Just taking a look at your wireframes and they look good, although I'm wondering what all is going in the sidebar menu, is that replacing a traditional header nav? |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>| N/A|
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. |N/A|

**Comment by pawaitemadisoncollege** [comment]
@salamarche and @timzschernitz One quick thing to add, it's standard to place the .gitignore file at the root of the project; it would be a good idea to move it out of the src directory:

<img width="1163" alt="Screen Shot 2021-02-28 at 5 27 51 PM" src="https://user-images.githubusercontent.com/13874466/109437588-25992100-79eb-11eb-93fc-f992dae24c11.png">

**Comment by distillers86** [comment]
> @salamarche and @timzschernitz One quick thing to add, it's standard to place the .gitignore file at the root of the project; it would be a good idea to move it out of the src directory:
> 
> <img alt="Screen Shot 2021-02-28 at 5 27 51 PM" width="1163" src="https://user-images.githubusercontent.com/13874466/109437588-25992100-79eb-11eb-93fc-f992dae24c11.png">

Thanks for the heads up! I will be sure to move that file back out to the project root folder.

**Comment by distillers86** [comment]
@salamarche I think you're right on the wording in the problem statement could be retooled a bit. It might be more accurate to say historical game data which ultimately would cover what will all be stored within the application.  You also make a good point on the navigation menu that maybe I need to rethink.  It might be more clean and modern to just implement a responsive nav bar at the top instead.
