### ISSUE TITLE
Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by distillers86** [timzschernitz/pokerStats#4]
@pawaitemadisoncollege Indie project checkpoint 2 is ready for review. Database  design is finished and implemented minus the updates I'll need to make for tomcat authentication. I've added a pdf diagram in the project-flow-and-wireframes which is numbered 13. So far I've created a User and Game class with GenericDao covering both for data access. I've only completed full testing for the User class and a bit of the Game class. No System.out.print lines are present. 

I appreciate the suggestions you've made along the way on my weekly follow along exercises and plan to implement them while making significant progress during the spring break week ahead of where my project is now. If there's anything I've missed in this check point or any further suggestions, I would appreciate them.

**Comment by pawaitemadisoncollege** [comment]
Nice job hitting checkpoint 2, @timzschernitz 

Good to see that you've implemented the generic dao already and have been keeping your time log up-to-date.

- [ ] How are you feeling about your project plan? Do any tasks need to move forward, such as the front end work? 

- [ ] A couple questions about the db design:
1.  Would it make sense to have a league table?
2.  Would it make sense to have a game table, with a join table between user and game? 
That may add some complexity that you don't need for V1 user stories, but wanted to check just in case.

**Comment by distillers86** [comment]
@pawaitemadisoncollege Sorry for my late reply, I saw this when you first posted the reply and meant to comment back much sooner. 

I do believe I need to readjust my project plan a bit so I'll be revisiting that today and making adjustments. As for the database design, I think those are some good suggestions and would likely solve some initial minor frustrations I had when actually creating the DB initially. I may see if I can get by with how it's designed for now and either add this as a future enhancement pre due date or post depending on how work on the indie project progresses overall.

**Comment by pawaitemadisoncollege** [comment]
Sounds good @timzschernitz!
