### ISSUE TITLE
Indie Project Ready for Checkpoint #3 Review

### ISSUE THREAD

**Issue by distillers86** [timzschernitz/pokerStats#5]
@pawaitemadisoncollege my indie project is ready for checkpoint 3 review. 

**Project has been deployed to AWS:**
- http://3.131.161.24:8080/Indie-Project-Poker-Stat-Tracking/

**Instructions:**
- Registration is not yet functional but there are 3 users that can be used to login in the meantime

1. pokerstar / pass000
2. bigspender21 / pass111
3. stacksOcash / pass222

- Once logged in, the only feature I have partially functioning, as in it's pulling users profile data but not pretty, is under the nav menu item My Profile > View My Profile
- Once in View My Profile, you should see the users name, location, and league they're joined in. 
- Aside from that, if you wanted to take a look at authentication, the application should be locked down to only allow users who are considered registered or an admin to get anywhere past the index page (aside from registration as my next up feature to work on). A failed login attempt does have a temporary message added below the login box to enhance the user experience. 

**Timelog and project plan:**
- My timelog has been updated as well as my project plan. I've also moved cards along on my kanban board found under the project readme though I will admin that I think I need to go through the tasks I've created and refine those as well. Having really dug into the project at a deeper level this last week helped me realize a better understanding of how I want the app to function. 
- Please let me know if there are any issues or suggestions.

**Comment by pawaitemadisoncollege** [comment]
All right @timzschernitz! You've hit CP3! 

At this point you have the core built and deployed and you should be set up well for adding more functionality.  I think your next step of adding registration is a good one, as you'll have the create and view cases hit.  Update will be similar to create and you'll probably be able to use some of the create forms/flow for updating.  Looking forward to seeing the next stages of this!

**Comment by pawaitemadisoncollege** [comment]
Love the user names too! :)
