### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Kharsla** [timzschernitz/pokerStats#8]
# Design/Code Review 2

#### Reviewer: Kaitlyn Harsla

|Category|Criteria|Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned MVP functionality has been met? | Login page, login ability, View profile, Navigation menu |
|| What planned MVP functionality has not been met? |Register User, Leaderboard, Individual stats view|
|| Logging framework used, i.e., no System.out.println() or printStacktrace() statements.|Yes|
||Hibernate used for all data access.|Yes|
||Authentication/Authorization implemented. |Yes|
||Consumes at least one web service or public api using Java.|Yes|
||Application is database-driven using full CRUD.| Delete, update, create was only found in Dao not yet implemented in project, Read is implemented in the leaderboard|
||Database includes multiple one to many relationships.|Only one one-to-many relationship between Game and user. No other relationships found.|
||Deployed to AWS for public access.||
||Implements best practices (for example, data validation - front end and back end)  |Error message is included for login.|
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| I’m going to be a hypocrite here and say that there aren’t many commits throughout the semester. Starting in end of march though you have been working on this more. Work aligns with checkpoints. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| Good job with incorporating feedback. The updated nav from and having it in an aside to the top bar was a good call. |
||Other comments/notes| |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel, responsiveness, accessibility.|In your profile.jsp do you plan on adding an option to change location or league? That could meeting your Update requirement for CRUD if you don’t already have a plan to implement somewhere else. Index looks good, its good you have an option to login and register on the homepage |
||Other comments/notes?| |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis
||single-purpose methods |Single purpose methods that are there are well written and clean.|
||well-structured project |It looks great so far. It is hard to see the flow of the project as a lot of the back end is missing but based on how you set up the login it looks great.|
||descriptive naming of packages, classes, methods, variables|I have never played poker so some variable names seem odd to me such as “buy_in_paid” but its hard to critique when I don’t know the terms used in poker. Methods, classes, etc are well written. The class “RegisterAction” not sure if the “action” is necessary in the name. | 
||classes appropriately-sized  (no monster classes or methods) |Most of the classes that are completed are not monster classes. Depending how you are setting it up a lot could end up in controller classes so use caution to not turn those in to monster classes.|CPD (copy paste detection, meaning are the same lines of code repeated?) |No CPD detected. You already did a great job by creating the LookupService to prevent repetitive code.|
||are there candidates for super/subclass relationships, abstract classes, interfaces? |I did not find any candidates for super/subclass relationships|
||are any values hard-coded that should be in a properties file? |No hard-coded values observed. |
||proper exception handling ||
||proper error reporting to the user |Good job with the error reporting when signing in. Other error handling will be needed when you get to those steps such as confirming if username already exists for users signing up
||code documentation ||
||is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? |There is not much in the doGet/DoPosts yet but so far there is nothing that could be refactored.|
|**Unit Tests**|Evaluate the unit tests, for example: 
|| tests are truly a unit test rather than a high level functional test|Tests are well written and unit tests|
|| test data is appropriately cleaned up and reset|Good job with the setup in tests. Is running each sql script independently necessary? I think you can put them all in one file.|
|| there is full coverage of methods that perform business logic or utility functions | Tests are missing in the UserDaoTest and Service Classes. As some are commented out though, I'm assuming this is in the works.|
||redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After|@Before is well utilized|
||Additional Comments|GenericDao line113 @return Javadoc is missing description. I Additional Comments I used the QAPlug and analyzed everything. Good job so far! Everything looked clean and it returned very few errors. Most errors were associated with unused imports due to commented out code and errors that did not appear to be errors. |

**Comment by distillers86** [comment]
@Kharsla thanks a lot for taking a look through my project and for the feedback. I can imagine it was challenging to provide feedback with so many pieces of the project still missing but I do appreciate your comments and will look to implement suggestions as I continue developing towards the final product.
